// Code generated by protoc-gen-go.
// source: ambition.proto
// DO NOT EDIT!

/*
Package ambition is a generated protocol buffer package.

It is generated from these files:
	ambition.proto

It has these top-level messages:
	CreateActionRequest
	CreateActionResponse
	CreateOccurrenceRequest
	CreateOccurrenceResponse
*/
package ambition

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/adamryman/ambition-truss/service/DONOTEDIT/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateActionRequest struct {
	UserId     int64  `protobuf:"varint,1,opt,name=UserId,json=userId" json:"UserId,omitempty"`
	ActionName string `protobuf:"bytes,2,opt,name=ActionName,json=actionName" json:"ActionName,omitempty"`
}

func (m *CreateActionRequest) Reset()                    { *m = CreateActionRequest{} }
func (m *CreateActionRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateActionRequest) ProtoMessage()               {}
func (*CreateActionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateActionResponse struct {
	ActionId int64 `protobuf:"varint,1,opt,name=ActionId,json=actionId" json:"ActionId,omitempty"`
}

func (m *CreateActionResponse) Reset()                    { *m = CreateActionResponse{} }
func (m *CreateActionResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateActionResponse) ProtoMessage()               {}
func (*CreateActionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CreateOccurrenceRequest struct {
	ActionId int64 `protobuf:"varint,1,opt,name=ActionId,json=actionId" json:"ActionId,omitempty"`
	EpocTime int64 `protobuf:"varint,2,opt,name=EpocTime,json=epocTime" json:"EpocTime,omitempty"`
}

func (m *CreateOccurrenceRequest) Reset()                    { *m = CreateOccurrenceRequest{} }
func (m *CreateOccurrenceRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateOccurrenceRequest) ProtoMessage()               {}
func (*CreateOccurrenceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type CreateOccurrenceResponse struct {
	OccurrenceId int64 `protobuf:"varint,1,opt,name=OccurrenceId,json=occurrenceId" json:"OccurrenceId,omitempty"`
	ActionId     int64 `protobuf:"varint,2,opt,name=ActionId,json=actionId" json:"ActionId,omitempty"`
}

func (m *CreateOccurrenceResponse) Reset()                    { *m = CreateOccurrenceResponse{} }
func (m *CreateOccurrenceResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateOccurrenceResponse) ProtoMessage()               {}
func (*CreateOccurrenceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*CreateActionRequest)(nil), "ambition.CreateActionRequest")
	proto.RegisterType((*CreateActionResponse)(nil), "ambition.CreateActionResponse")
	proto.RegisterType((*CreateOccurrenceRequest)(nil), "ambition.CreateOccurrenceRequest")
	proto.RegisterType((*CreateOccurrenceResponse)(nil), "ambition.CreateOccurrenceResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for AmbitionService service

type AmbitionServiceClient interface {
	CreateAction(ctx context.Context, in *CreateActionRequest, opts ...grpc.CallOption) (*CreateActionResponse, error)
	CreateOccurrence(ctx context.Context, in *CreateOccurrenceRequest, opts ...grpc.CallOption) (*CreateOccurrenceResponse, error)
}

type ambitionServiceClient struct {
	cc *grpc.ClientConn
}

func NewAmbitionServiceClient(cc *grpc.ClientConn) AmbitionServiceClient {
	return &ambitionServiceClient{cc}
}

func (c *ambitionServiceClient) CreateAction(ctx context.Context, in *CreateActionRequest, opts ...grpc.CallOption) (*CreateActionResponse, error) {
	out := new(CreateActionResponse)
	err := grpc.Invoke(ctx, "/ambition.AmbitionService/CreateAction", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ambitionServiceClient) CreateOccurrence(ctx context.Context, in *CreateOccurrenceRequest, opts ...grpc.CallOption) (*CreateOccurrenceResponse, error) {
	out := new(CreateOccurrenceResponse)
	err := grpc.Invoke(ctx, "/ambition.AmbitionService/CreateOccurrence", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AmbitionService service

type AmbitionServiceServer interface {
	CreateAction(context.Context, *CreateActionRequest) (*CreateActionResponse, error)
	CreateOccurrence(context.Context, *CreateOccurrenceRequest) (*CreateOccurrenceResponse, error)
}

func RegisterAmbitionServiceServer(s *grpc.Server, srv AmbitionServiceServer) {
	s.RegisterService(&_AmbitionService_serviceDesc, srv)
}

func _AmbitionService_CreateAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmbitionServiceServer).CreateAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambition.AmbitionService/CreateAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmbitionServiceServer).CreateAction(ctx, req.(*CreateActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AmbitionService_CreateOccurrence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOccurrenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmbitionServiceServer).CreateOccurrence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ambition.AmbitionService/CreateOccurrence",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmbitionServiceServer).CreateOccurrence(ctx, req.(*CreateOccurrenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AmbitionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ambition.AmbitionService",
	HandlerType: (*AmbitionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAction",
			Handler:    _AmbitionService_CreateAction_Handler,
		},
		{
			MethodName: "CreateOccurrence",
			Handler:    _AmbitionService_CreateOccurrence_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("ambition.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xcc, 0x4d, 0xca,
	0x2c, 0xc9, 0xcc, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0xa5, 0x64,
	0xd2, 0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5, 0x13, 0x0b, 0x32, 0xf5, 0x13, 0xf3, 0xf2, 0xf2, 0x4b,
	0x12, 0x41, 0xc2, 0xc5, 0x10, 0x75, 0x4a, 0xbe, 0x5c, 0xc2, 0xce, 0x45, 0xa9, 0x89, 0x25, 0xa9,
	0x8e, 0xc9, 0x20, 0xe1, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x31, 0x2e, 0xb6, 0xd0,
	0xe2, 0xd4, 0x22, 0xcf, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xe6, 0x20, 0xb6, 0x52, 0x30, 0x4f,
	0x48, 0x8e, 0x8b, 0x0b, 0xa2, 0xd0, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x09, 0x28, 0xc7, 0x19, 0xc4,
	0x95, 0x08, 0x17, 0x51, 0x32, 0xe2, 0x12, 0x41, 0x35, 0xae, 0xb8, 0x00, 0x68, 0x57, 0xaa, 0x90,
	0x14, 0x17, 0x07, 0x44, 0x04, 0x6e, 0x22, 0x47, 0x22, 0x94, 0xaf, 0x14, 0xc8, 0x25, 0x0e, 0xd1,
	0xe3, 0x9f, 0x9c, 0x5c, 0x5a, 0x54, 0x94, 0x9a, 0x97, 0x9c, 0x0a, 0x73, 0x06, 0x1e, 0x6d, 0x20,
	0x39, 0xd7, 0x82, 0xfc, 0xe4, 0x90, 0x4c, 0xa8, 0x43, 0x80, 0x72, 0xa9, 0x50, 0xbe, 0x52, 0x14,
	0x97, 0x04, 0xa6, 0x91, 0x50, 0xa7, 0x28, 0x71, 0xf1, 0x20, 0x44, 0xe1, 0xe6, 0xf2, 0xe4, 0x23,
	0x89, 0xa1, 0xd8, 0xcb, 0x84, 0x6a, 0xaf, 0xd1, 0x3b, 0x46, 0x2e, 0x7e, 0x47, 0x68, 0xe0, 0x06,
	0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0x25, 0x72, 0xf1, 0x20, 0x7b, 0x5b, 0x48, 0x56, 0x0f,
	0x1e, 0x1d, 0x58, 0x42, 0x57, 0x4a, 0x0e, 0x97, 0x34, 0xc4, 0x89, 0x4a, 0x42, 0x4d, 0x97, 0x9f,
	0x4c, 0x66, 0xe2, 0x51, 0x62, 0xd7, 0x87, 0xd8, 0x6a, 0xc5, 0xa8, 0x25, 0x54, 0xc1, 0x25, 0x80,
	0xee, 0x25, 0x21, 0x45, 0x74, 0x73, 0x30, 0x42, 0x50, 0x4a, 0x09, 0x9f, 0x12, 0xa8, 0x75, 0xb2,
	0x60, 0xeb, 0xc4, 0x95, 0x84, 0xa0, 0xd6, 0xe9, 0x57, 0xc3, 0x3c, 0x5f, 0x0b, 0xb4, 0x39, 0x89,
	0x0d, 0x9c, 0x52, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xfd, 0xb1, 0xf5, 0xa9, 0x63, 0x02,
	0x00, 0x00,
}
